CREATE TABLE public.beads (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying,
  colour character varying,
  shape character varying,
  diameter_mm integer,
  image_path text NOT NULL,
  stock bigint NOT NULL,
  price integer NOT NULL, -- Price in cents
  CONSTRAINT beads_pkey PRIMARY KEY (id)
);

CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email character varying NOT NULL UNIQUE,
  name character varying,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  price integer NOT NULL,
  status text NOT NULL,
  
  -- nullable fields filled after payment
  customer_id bigint,
  country character varying,
  postal_code character varying,
  date_ordered timestamp without time zone DEFAULT now(),  
  customer_email character varying,
  customer_name character varying,
  delivery_method character varying,
  session_id character varying,

  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);

CREATE TABLE public.orders_beads (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_id bigint NOT NULL,
  bead_id bigint NOT NULL,
  CONSTRAINT orders_beads_pkey PRIMARY KEY (id),
  CONSTRAINT orders_beads_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT orders_beads_bead_id_fkey FOREIGN KEY (bead_id) REFERENCES public.beads(id)
);